# -*- coding: utf-8 -*-
"""Validação_CPF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bHi42gNRAPo7FJYT9bwBYL4Ts6IhfGY4
"""

def validar_cpf(cpf: str) -> bool:
    cpf = re.sub(r'\D', '', cpf)

    if len(cpf) != 11 or cpf == cpf[0] * 11:
        return False

    soma = sum(int(cpf[i]) * (10 - i) for i in range(9))
    digito1 = (soma * 10 % 11) % 10
    if digito1 != int(cpf[9]):
        return False

    soma = sum(int(cpf[i]) * (11 - i) for i in range(10))
    digito2 = (soma * 10 % 11) % 10
    if digito2 != int(cpf[10]):
        return False

    return True

def validar_rg(rg: str) -> bool:
    rg = re.sub(r'\D', '', rg)
    return 7 <= len(rg) <= 9


cpf_usuario = input("Digite seu CPF (com ou sem pontuação): ")
rg_usuario = input("Digite seu RG (com ou sem pontuação): ")


if validar_cpf(cpf_usuario):
    print("CPF válido!")
else:
    print("CPF inválido.")

if validar_rg(rg_usuario):
    print("RG válido!")
else:
    print("RG inválido.")